config/routes.rb
Photogal::Application.routes.draw do
  resources :favorites

  resources :notifications
  resources :relationships, :only => [:create, :destroy, :show]
  resources :favorites, :only => [:create, :destroy, :show]
  resources :comments

  get "dorms/new"

  get "schools/new"

  get "colleges/new"
  get "tags/new"
  get "notifications/index"

  resources :users do
      member do
        get :following, :followers
      end
  end
    
  resources :colleges
  resources :schools
  resources :dorms
  resources :photos , {:except => :index} do
    resources :comments
  end
  resources :tags
  resources :sessions, :only => [:new, :create, :destroy]
  
  root :to => 'pages#home'
  
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "sessions/new"
  get "sessions/destroy"
  get "photos/upload"
  get "photos/index"
  
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/upload', :to => 'photos#new'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :photo
  has_many :notifications
  
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html 
      
    end
  end

 
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html 
     
    end
  end

  def new
    @comment = Comment.new

    respond_to do |format|
      format.html 
      
    end
  end
  
  def edit
    @comment = Comment.find(params[:id])
  end

 
  def create
    if signed_in?
      @photo=Photo.find(params[:photo_id])
      @comment = Comment.new(:comment=>params[:comment][:comment], :user_id=>current_user.id, :photo_id=>Photo.find(params[:photo_id]).id)
      
      respond_to do |format|
        if @comment.save
          unless Photo.find(@comment.photo_id).user_id==current_user.id
            Notification.create!(:user_id=>Photo.find(@comment.photo_id).user.id, :comment_id=>@comment.id)
          end
          format.html { redirect_to(@photo) }
        
          format.html { render :action => "new" }
       
        end
      end
    end
  end

  
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(@comment, :notice => 'Comment was successfully updated.') }
       
      else
        format.html { render :action => "edit" }
        
      end
    end
  end

  
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    @photo=Photo.find(@comment.photo_id)
    respond_to do |format|
      format.html { redirect_to(@photo) }
    
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@photo, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="newcomment">
  	<div class="field">
	    <%= f.text_area :comment, :size => "65x5" %>
	  </div>
	  <div class="actions">
	    <%= f.submit %>
	  </div>
	</div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Photo</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.photo_id %></td>
    <td><%= comment.comment %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Photo:</b>
  <%= @comment.photo_id %>
</p>

<p>
  <b>Comment:</b>
  <%= @comment.comment %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>