config/routes.rb
Photogal::Application.routes.draw do
  resources :favorites

  resources :notifications
  resources :relationships, :only => [:create, :destroy, :show]
  resources :favorites, :only => [:create, :destroy, :show]
  resources :comments

  get "dorms/new"

  get "schools/new"

  get "colleges/new"
  get "tags/new"
  get "notifications/index"

  resources :users do
      member do
        get :following, :followers
      end
  end
    
  resources :colleges
  resources :schools
  resources :dorms
  resources :photos , {:except => :index} do
    resources :comments
  end
  resources :tags
  resources :sessions, :only => [:new, :create, :destroy]
  
  root :to => 'pages#home'
  
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "sessions/new"
  get "sessions/destroy"
  get "photos/upload"
  get "photos/index"
  
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/upload', :to => 'photos#new'
  

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
  belongs_to :comment
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  # GET /notifications
  # GET /notifications.xml
  def index
    @notifications = current_user.notifications
 

    respond_to do |format|
      format.html # index.html.erb
      #format.xml  { render :xml => @notifications }
    end
  end

  # GET /notifications/1
  # GET /notifications/1.xml
  def show
    @notification = Notification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      #format.xml  { render :xml => @notification }
    end
  end

  # GET /notifications/new
  # GET /notifications/new.xml
  def new
    @notification = Notification.new

    respond_to do |format|
      format.html # new.html.erb
      #format.xml  { render :xml => @notification }
    end
  end

  # GET /notifications/1/edit
  def edit
    @notification = Notification.find(params[:id])
  end

  # POST /notifications
  # POST /notifications.xml
  def create
    @notification = Notification.new(params[:notification])

    respond_to do |format|
      if @notification.save
        format.html { redirect_to(@notification, :notice => 'Notification was successfully created.') }
       # format.xml  { render :xml => @notification, :status => :created, :location => @notification }
      else
        format.html { render :action => "new" }
       # format.xml  { render :xml => @notification.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /notifications/1
  # PUT /notifications/1.xml
  def update
    @notification = Notification.find(params[:id])

    respond_to do |format|
      if @notification.update_attributes(params[:notification])
        format.html { redirect_to(@notification, :notice => 'Notification was successfully updated.') }
       # format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
       # format.xml  { render :xml => @notification.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.xml
  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy

    respond_to do |format|
      format.html { redirect_to(notifications_url) }
     # format.xml  { head :ok }
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :photo_id %><br />
    <%= f.text_field :photo_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<h1>Listing notifications</h1>

<table>
  <tr>
    <th>Photo</th>
    <th></th>
  </tr>

<% @notifications.each do |notification| %>
  <tr>
    <td>

				<%=link_to Comment.find(notification.comment_id).user.first_name, User.find(Comment.find(notification.comment_id).user_id)%> 
				wrote 
				<%= link_to truncate(Comment.find(notification.comment_id).comment), Photo.find(Comment.find(notification.comment_id).photo_id) %>
	
		</td>

    
    <td><%= link_to 'Delete', notification, :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Photo:</b>
  <%= @notification.photo_id %>
</p>

<p>
  <b>Reciever:</b>
  <%= @notification.user_id %>
</p>


<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>