config/routes.rb
Photogal::Application.routes.draw do
  resources :favorites

  resources :notifications
  resources :relationships, :only => [:create, :destroy, :show]
  resources :favorites, :only => [:create, :destroy, :show]
  resources :comments

  get "dorms/new"

  get "schools/new"

  get "colleges/new"
  get "tags/new"
  get "notifications/index"

  resources :users do
      member do
        get :following, :followers
      end
  end
    
  resources :colleges
  resources :schools
  resources :dorms
  resources :photos , {:except => :index} do
    resources :comments
  end
  resources :tags
  resources :sessions, :only => [:new, :create, :destroy]
  
  root :to => 'pages#home'
  
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "sessions/new"
  get "sessions/destroy"
  get "photos/upload"
  get "photos/index"
  
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/upload', :to => 'photos#new'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  columbia_regex = /\A(([a-zA-Z]{2,3})(\d{4})@columbia.edu)/i
  
  attr_accessor :password
  
  attr_accessible :first_name, :last_name, :email, :college_id , :password, :password_confirmation, :year, :school_id, :dorm_id
  
  has_many :photos, :dependent => :destroy
  
  
  has_many :comments, :dependent => :destroy
  has_many :notifications, :dependent => :destroy
  has_many :relationships, :foreign_key => "follower_id",
                             :dependent => :destroy
  has_many :following, :through => :relationships, :source => :followed
  has_many :reverse_relationships, :foreign_key => "followed_id",
                                     :class_name => "Relationship",
                                     :dependent => :destroy
  has_many :followers, :through => :reverse_relationships, :source => :follower     
  has_many :favorites                    
  belongs_to :college
  belongs_to :dorm
  belongs_to :school
  
  validates :first_name, :presence => true, :length   => { :maximum => 30 }
  validates :last_name, :presence => true, 
                        :length   => { :maximum => 30 }
  validates :email, :presence => true,
                    :format     => { :with => columbia_regex, :message => "is not a college email address" },
                    :uniqueness => true
  validates :college_id, :presence => true
  validates :dorm_id, :presence => true
  validates :year, :presence => true
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }
  
  before_save :encrypt_password
  before_save :downcase_email
  
  def downcase_email
    self.email.downcase!
  end

  def has_password?(submitted_password)
     encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
        user = find_by_email(email)
        return nil  if user.nil?
        return user if user.has_password?(submitted_password)
  end
      
  def self.authenticate(email, submitted_password)
      user = find_by_email(email)
      return nil  if user.nil?
      return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
  end
  
  def following?(followed)
      relationships.find_by_followed_id(followed)
  end

  def follow!(followed)
    relationships.create!(:followed_id => followed.id)
  end
  
  def unfollow!(followed)
      relationships.find_by_followed_id(followed).destroy
  end
  
  def feed
     Photo.from_users_followed_by(self)
  end
  
  
  def favoriting?(photo)
      favorites.find_by_photo_id(photo)
  end

  def favorite!(photo)
    favorites.create!(:photo_id => photo.id)
  end
  
  def unfavorite!(photo)
      favorites.find_by_photo_id(photo).destroy
  end
  
  

  private

  def encrypt_password
    self.salt = make_salt if new_record?
    self.encrypted_password = encrypt(password)
  end

  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end

  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy
  before_filter :authenticate, :except => [:show, :new, :create]
  
 
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @photos=@user.photos.order("created_at DESC").page(params[:page]).per(20)
    @list="My"
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
     @user = User.new(params[:user])
     if @user.save
       sign_in @user
       flash[:success] = "Welcome to College Collage!"
       redirect_to @user
     else
        if @user.errors.any?      
            errors="Please fix the error(s): <ul>"
            @user.errors.full_messages.each do |msg|
              errors<<"<il>" + msg +"</il><br>"
            end 
        end
        errors<<"</ul>"
        flash[:error]=errors.html_safe
       redirect_to signup_path
     end 
  end

  def update
         @user = User.find(params[:id])
         if @user.update_attributes(params[:user])
           flash[:success] = "Profile updated."
           redirect_to @user
         else
           render 'edit'
         end
  end

  def following
     @title = "Following"
     @user = User.find(params[:id])
     @users = @user.following.page(params[:page]).per(50)
     render 'show_follow'
   end
   
   def followers
       @title = "Followers"
       @user = User.find(params[:id])
       @users = @user.followers.page(params[:page]).per(50)
       render 'show_follow'
     end 


  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end
  
  private

     def authenticate
         deny_access unless signed_in?
     end
     
     def correct_user
          @user = User.find(params[:id])
          redirect_to(root_path) unless current_user?(@user)
     end
   
     def admin_user
           redirect_to(root_path) unless current_user.admin?
     end
    
end

app/helpers/users_helper.rb
module UsersHelper
  
 
end

app/views/users/_follow.html.erb
<%= form_for current_user.relationships.build(:followed_id => @user.id),
             :remote => true do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <div class="actions"><%= f.submit "Follow" %></div>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<% javascript 'dynamic_schools'%>
<%= form_for(@user) do |f| %>

<div id="signup">

<p>Dear Random Class Mate, </p>
	<p class="indent">Hey. So I figure we should know a little bit about each other before I graduate in <%= f.select :year, [['2010', 2010], ['2011', 2011], ['2012', 2012], ['2013', 2013], ['2014', 2014], ['2015', 2015]], :prompt => "Year"%>. I'll let you know a little about me now, but you'll really get to know me when I start posting pictures. Obviously you know that I go to <%= f.collection_select :college_id, College.all, :id, :name, :prompt => "Select a College"%>, but you might not have known that I'm in <%= f.collection_select :school_id, School.all, :id, :name, :prompt => "Select a School" %>. I live in <%= f.collection_select :dorm_id, Dorm.all, :id, :name, :prompt => "Select a Dorm" %>, which is pretty great. Anyways, if you want to reach me just shoot me an email at <%= f.text_field :email, :size=> "20"  %> and I'll get back to you! </p><br>
		<p class="indent">Sincerely, <%= f.text_field :first_name, :size=> "10" %> 
		 <%= f.text_field :last_name, :size=> "10"  %></p>
		
		<p class="indent">P.S. Let me tell you a secret! Last weekend I sharpied 
		<%= f.password_field :password, :size=> "15"  %> 
		on the bathroom wall! That's right, 
		<%= f.password_field :password_confirmation, :size=> "15"  %>
		!</p>
  
	
  
	
	
  
  <div class="actions">
    <center><%= f.submit "Send" %></center>
  </div>
<% end %>
</div>

app/views/users/_unfollow.html.erb
<%= form_for current_user.relationships.find_by_followed_id(@user),
             :html => { :method => :delete },
             :remote => true do |f| %>
  <div class="actions"><%= f.submit "Unfollow" %></div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>


<%= form_for(@user) do |f| %>
<p>

	First Name: <%= f.text_field :first_name %> <br>
	Last Name: <%= f.text_field :last_name %> <br>
	Year: <%= f.select :year, [['2010', 2010], ['2011', 2011], ['2012', 2012], ['2013', 2013], ['2014', 2014], ['2015', 2015]]%> <br>
	School: <%= f.collection_select :school_id, School.all, :id, :name, :prompt => "Select a School" %> <br>
	Dorm: <%= f.collection_select :dorm_id, Dorm.all, :id, :name, :prompt => "Select a Dorm" %>. <br>
		
	Email: <%= f.text_field :email %> <br>
	
	Password: <%= f.password_field :password %> <br>
 
	Password Confirmation: <%= f.password_field :password_confirmation %><br>

  
	
  
	
	
  
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>College</th>
    <th>Class</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.email %></td>
    <td><%= user.college_id %></td>
    <td><%= user.class %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<% if signed_in?%>
<p id="notice"><%= notice %></p>
<center>
	<h1><%= @user.first_name %> <%= @user.last_name %></h1>
	<h3><%= college %>, <%= School.find(@user.school_id).name %> <%= @user.year %></h3>
	<p><%= pluralize(@user.followers.count,  "person") %> following</p>
</center>


<%= render 'follow_form' %>

<%= render 'shared/index' %>



<%else%>
<%= render 'shared/signin'%>
<%end%>

app/views/users/show_follow.html.erb
<table summary="Information about following/followers">
  <tr>
    <td class="main">
      <h1><%= @title %></h1>

      <% unless @users.empty? %>
        <ul class="users">
          <%= render @users %>
        </ul>
        <%= will_paginate @users %>
      <% end %>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= name(@user) %><br />
      <strong>URL</strong> <%= link_to user_path(@user), @user %><br />
      <strong>Photos</strong> <%= @user.photos.count %>
    
      
    </td>
  </tr>
</table>